spring:
  datasource:
    password: ${DB_PASSWORD:} #default is empty string for local
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:spring_app}
    username: ${DB_USERNAME:root}
#    data: classpath:import.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
application:
  security:
    jwt-secret: ${JWT_SECRET:MYJWTSECRET123}
    issuer: ${JWT_ISSUER:PartyStarterInc}
  seeding:
    should-seed: ${SHOULD_SEED:false}
#    interval: ${SEED_INTERVAL:60000} #cant inject value to fixedRate param on Scheduler
  cocktail-db:
    url: https://www.thecocktaildb.com
    apikey: ${COCKTAIL_DB_API_KEY:1} #free API Key is '1'
  spotify:
    auth:
      client-id: d0982bc6c139493bbe74eee8d2ddd811
      client-secret: 71e38651417d4691847c3759f6ee46a4
      url: https://accounts.spotify.com
    url: https://api.spotify.com
logging:
  level:
    root: ${LOGGING_LEVEL:info}
#server:
#  port: 8080
#  address: 192.168.20.176