spring:
  datasource:
    password: ${DB_PASSWORD:} #default is empty string for local
    url: jdbc:mysql://${DB_HOST:localhost:3306/spring_app}
    username: ${DB_USERNAME:root}
#    data: classpath:import.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

application:
  seeding:
    should-seed: ${SHOULD_SEED:false}
    interval: ${SEED_INTERVAL:60000}
  cocktail-db:
    url: https://www.thecocktaildb.com
    apikey: ${COCKTAIL_DB_API_KEY:1} #free API Key is '1'
  spotify:
    auth:
      client-id: ee225924105b4363802728d60bda8c6c
      client-secret: cfbc9140eafd488da9791294833bcd28
      url: https://accounts.spotify.com
    url: https://api.spotify.com
logging:
  level:
    root: ${LOGGING_LEVEL:info}