spring:
  datasource:
    password: ''
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_app
    username: root
#    data: classpath:import.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

application:
  should-seed: ${SHOULD_SEED:true}