spring:
  datasource:
    password: ''
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_app
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
