name: Deploy Spring Boot Backend

on:
  push:
    branches: [ master ]
    paths:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: party-starter
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests

      - name: Copy JAR to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*.jar"
          target: "/tmp"
          strip_components: 2

      - name: Deploy Spring Boot app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop springapp
            sudo mv /tmp/*.jar /var/www/backend/app.jar
            sudo systemctl start springapp
            sudo systemctl status springapp --no-pager